version: '3.3'

networks:
  web:
    driver: bridge

services:
### php ###############################################
    php:
      image: cffycls/php
      volumes:
        - ./php/:/usr/local/php/etc/
      networks:
        - web

### NGINX Server #########################################
    nginx:
      image: openresty/openresty
      volumes:
        - ./nginx/conf/:/usr/local/openresty/nginx/conf/
        - ./nginx/logs/:/usr/local/openresty/nginx/logs/
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      networks:
        - web

### MySQL ################################################
    mysql:
      image: mysql:8.0
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ./mysql/data/:/var/lib/mysql/
        - ./mysql/config/:/etc/mysql/
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - web

### Redis ################################################
    redis:
      image: redis:6.0.4
      volumes:
        - ./redis/:/data/
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - web

### Redis Cluster ##########################################
    redis-cluster:
      image: grokzen/redis-cluster:latest
      ports:
        - "${REDIS_CLUSTER_PORT_RANGE}:7001-7006"
      networks:
        - web

### phpMyAdmin ###########################################
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=${PMA_USER}
        - MYSQL_PASSWORD=${PMA_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      ports:
        - "${PMA_PORT}:80"
      depends_on:
        - "${PMA_DB_ENGINE}"
      networks:
        - web

### REDISWEBUI ################################################
    redis-webui:
      image: erikdubbelboer/phpredisadmin
      environment:
        - ADMIN_USER=${REDIS_WEBUI_USERNAME}
        - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
        - REDIS_1_HOST=redis
        - REDIS_1_PORT=6379
      networks:
        - web
      ports:
        - "${REDIS_WEBUI_PORT}:80"
      depends_on:
        - redis
